In [1]:
from torch import FloatTensor
from torch.autograd import Variable

#### torch.autograd

autograd.Variable class : wrap Tensor   
- .data : You can approach *raw tensor*
- .grad : gradient data (if you use ".backward()")
- .grad_fn

https://towardsdatascience.com/getting-started-with-pytorch-part-1-understanding-how-automatic-differentiation-works-5008282073ec

In [ ]:
# Define the leaf nodes
a = Variable(FloatTensor([4]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

# unpack the weights for nicer assignment
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

L.backward()

In [35]:
L

tensor([-202.], grad_fn=<RsubBackward1>)

In [36]:
L.data

tensor([-202.])

In [52]:
print(L.grad_fn)
print(d.grad_fn)
print(c.grad_fn)
print(b.grad_fn)

In [26]:
weights

[tensor([2.], requires_grad=True),
 tensor([5.], requires_grad=True),
 tensor([9.], requires_grad=True),
 tensor([7.], requires_grad=True)]

In [47]:
for index, weight in enumerate(weights, start=1): # index start point
    print(index, weight)
    
    print(weight.grad)
    print(weight.grad.data)
    gradient, *_ = weight.grad.data
    print(gradient)
    
    print(f"Gradient of w{index} w.r.t to L: {gradient}\n")   

1 tensor([2.], requires_grad=True)
tensor([-36.])
tensor([-36.])
tensor(-36.)
Gradient of w1 w.r.t to L: -36.0

2 tensor([5.], requires_grad=True)
tensor([-28.])
tensor([-28.])
tensor(-28.)
Gradient of w2 w.r.t to L: -28.0

3 tensor([9.], requires_grad=True)
tensor([-8.])
tensor([-8.])
tensor(-8.)
Gradient of w3 w.r.t to L: -8.0

4 tensor([7.], requires_grad=True)
tensor([-20.])
tensor([-20.])
tensor(-20.)
Gradient of w4 w.r.t to L: -20.0

